### ISSUE TITLE
nexpy doesn not work with ipython 2.1.0

### ISSUE THREAD

**Issue by picca** [nexpy/nexpy#30]
Hello, as usual once a while I test nexpy :)
So here is the error message that I get when I try to run nexpy from the source directory.

Cheers

Frederic

picca@mordor:~/Projets/nexpy/src/nexpy$ ./nexpygui.py 
Traceback (most recent call last):
  File "./nexpygui.py", line 28, in <module>
    main()
  File "./nexpygui.py", line 24, in main
    main()
  File "/home/picca/Projets/nexpy/src/nexpy/gui/consoleapp.py", line 312, in main
    app.initialize()
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/home/picca/Projets/nexpy/src/nexpy/gui/consoleapp.py", line 293, in initialize
    self.init_colors()
  File "/home/picca/Projets/nexpy/src/nexpy/gui/consoleapp.py", line 232, in init_colors
    colors=colors.lower()
AttributeError: 'LazyConfigValue' object has no attribute 'lower'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

picca@mordor:~/Projets/nexpy/src/nexpy$ ipython --version
2.1.0
